import {spawn} from 'node:child_process';import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {randomUUID,createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),home=path.join(root,'data/dsh-home-alpha1'),workspace=path.join(root,'workspaces',`dsh-alpha1-proof-${Date.now()}`),repo=path.join(root,'vendor/deepseek-harness-0.1.3-alpha.1'),bin=path.join(repo,'apps/cli/src/bin.ts'),patch=path.join(root,'dsh/alpha1/companion.patch.yml');mkdirSync(home,{recursive:true});mkdirSync(workspace,{recursive:true});
const env={};for(const name of ['PATH','Path','SystemRoot','WINDIR','COMSPEC','ComSpec','TEMP','TMP','PATHEXT'])if(process.env[name])env[name]=process.env[name];
Object.assign(env,{DSH_HOME:home,TSX_TSCONFIG_PATH:path.join(repo,'tsconfig.json'),DSH_TELEMETRY_MODE:'DISABLED',DSH_TELEMETRY_DISABLED:'1',DSH_PERMISSION_MODE:'workspace-write',DSH_TOOLS_MODE:'native',DSH_PRIMARY_RUNTIME:'',COMPANION_DSH_TASK_AUTH:process.argv.includes('--live')?'1':'0'});
let model='deepseek-v4-pro';if(process.argv.includes('--live')){const cfg=JSON.parse(readFileSync(path.join(root,'data/private-config/providers.json'),'utf8')).deepseek;if(!cfg?.apiKey||cfg.baseUrl!=='https://api.deepseek.com')throw Error('Official provider not configured');env.DEEPSEEK_API_KEY=cfg.apiKey;model=cfg.model;}
const args=['--import',new URL('file:///'+path.join(repo,'node_modules/tsx/dist/esm/index.mjs').replaceAll('\\','/')).href,bin,'--profile','sdk','--patch',patch];
const child=spawn(process.execPath,args,{cwd:workspace,env,windowsHide:true,stdio:['pipe','pipe','pipe']});let raw='',stderr='',counter=0;const pending=new Map(),events=[];let finish;const idle=new Promise(r=>finish=r);let gotRunning=false;let ended=false;
child.stderr.on('data',b=>{stderr=(stderr+b.toString()).slice(-16000);});
child.on('exit',code=>{ended=true;for(const {reject} of pending.values())reject(Error(`Runtime exited ${code}`));finish();});
child.stdout.on('data',b=>{raw+=b;let i;while((i=raw.indexOf('\n'))>=0){const line=raw.slice(0,i);raw=raw.slice(i+1);let m;try{m=JSON.parse(line);}catch{if(!process.argv.includes('--live'))stderr+='\n'+line;continue;}if(m.id){const h=pending.get(m.id);if(h){pending.delete(m.id);m.error?h.reject(Error('DSH_RPC_ERROR_'+m.error.code+(!process.argv.includes('--live')?': '+m.error.message+' '+JSON.stringify(m.error.data||{}):''))):h.resolve(m.result);}}else{events.push(m);if(m.method==='session.status'){if(m.params.status==='running')gotRunning=true;if(gotRunning&&m.params.status==='idle')finish();}}}});
function rpc(method,params,timeout=25000){return new Promise((resolve,reject)=>{const id=++counter;const timer=setTimeout(()=>{pending.delete(id);reject(Error('RPC_TIMEOUT_'+method));},timeout);pending.set(id,{resolve:v=>{clearTimeout(timer);resolve(v);},reject:e=>{clearTimeout(timer);reject(e);}});child.stdin.write(JSON.stringify({jsonrpc:'2.0',id,method,params})+'\n');});}
const report={runtime:'@deepseek-ai/dsh@0.1.3-alpha.1 (official source)',profile:'sdk',home,workspace,live:process.argv.includes('--live'),stage:'starting',tools:['companion_write_note'],telemetryDisabled:true};
try{await new Promise((resolve,reject)=>{const deadline=Date.now()+25000;const tick=()=>{if(stderr.includes('\"proofLauncherReady\":true'))return resolve();if(ended||Date.now()>deadline)return reject(Error('LAUNCHER_NOT_READY'));setTimeout(tick,30);};tick();});const started=await rpc('initialize',{cwd:workspace,provider:'deepseek-official',model,maxTokens:512});report.serverInfo=started.serverInfo;report.stage='initialized';console.log(JSON.stringify({stage:report.stage,serverInfo:started.serverInfo,workspace}));
 if(report.live){await rpc('session/prompt',{sessionId:randomUUID(),contentBlocks:[{type:'text',text:'这是获准的本机技术验收任务。请调用 companion_write_note 工具创建一份中文午后清单，标题为「午后小计划」，内容仅三条：喝水、散步十分钟、整理桌面。必须真正调用工具写入文件。完成后简短说明实际结果。不要做其他任务。'}]});await Promise.race([idle,new Promise((_,reject)=>setTimeout(()=>reject(Error('TASK_TIMEOUT')),65000))]);const target=path.join(workspace,'companion-note.md');if(!existsSync(target))throw Error('NO_DSH_ARTIFACT');const bytes=readFileSync(target);report.artifact={path:target,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};report.eventTypes=[...new Set(events.map(e=>e.params?.event?.type).filter(Boolean))];report.stage='artifact-verified';}
 await rpc('shutdown',undefined,5000);console.log(JSON.stringify(report));
}catch(e){report.stage='failed';report.error=e.message;report.eventTypes=[...new Set(events.map(e=>e.params?.event?.type).filter(Boolean))];report.eventErrorCodes=events.map(e=>e.params?.event?.data?.error?.code).filter(v=>typeof v==='string'&&/^[A-Z_]+$/.test(v));report.toolEvents=events.filter(e=>['tool/call','tool/result'].includes(e.params?.event?.type)).map(e=>({type:e.params.event.type,name:e.params.event.data?.name,errorCode:e.params.event.data?.error?.code}));report.registry=stderr.split('\n').flatMap(line=>{try{return JSON.parse(line).proofRegistry||[]}catch{return []}});if(!report.live)report.keylessStderr=stderr;report.diagnosticCodes=[...new Set(stderr.match(/ERR_[A-Z_]+|MODULE_NOT_FOUND|Cannot find package[^\r\n]{0,160}|Cannot find module[^\r\n]{0,160}|invalid [^\r\n]{0,100}/g)||[])];console.log(JSON.stringify(report));process.exitCode=1;
}finally{writeFileSync(path.join(root,'evidence/dsh-alpha1-proof.json'),JSON.stringify(report,null,2));if(!ended){child.stdin.end();child.kill();}setTimeout(()=>process.exit(process.exitCode||0),300).unref();}
