import {mkdirSync,readFileSync,writeFileSync,readdirSync,existsSync,renameSync} from 'node:fs';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import {workspaceFiles} from './workspace-files.mjs';import {validId} from './jobs.mjs';
const error=(message,status=400)=>Object.assign(new Error(message),{status});
export class AgentJobs{
 constructor(dataRoot,adapter){this.dir=path.join(dataRoot,'agent-jobs');this.downloads=path.join(dataRoot,'agent-artifacts');this.files=workspaceFiles(path.join(dataRoot,'workspace'),path.join(dataRoot,'file-backups'));this.adapter=adapter;this.jobs=new Map();this.controls=new Map();this.queue=Promise.resolve();mkdirSync(this.dir,{recursive:true});mkdirSync(this.downloads,{recursive:true});
  for(const f of readdirSync(this.dir).filter(f=>/^[a-f0-9-]{36}\.json$/.test(f))){const j=JSON.parse(readFileSync(path.join(this.dir,f),'utf8'));if(!validId(j.id))continue;if(['queued','running','waiting-approval'].includes(j.state)){j.state='interrupted';j.pending=null;j.revision++;this.persist(j);}this.jobs.set(j.id,j);}
 }
 persist(j){const file=path.join(this.dir,j.id+'.json');writeFileSync(file+'.tmp',JSON.stringify(j),{mode:0o600});renameSync(file+'.tmp',file);}
 event(j,type,summary,extra={}){j.events.push({sequence:j.events.length+1,time:new Date().toISOString(),type,summary:summary.slice(0,300),...extra});if(j.events.length>100)j.events.shift();j.revision++;this.persist(j);}
 create({id,turnId,requestId,text,history=[]}){if(this.closed)throw error('服务正在关闭',503);if(!validId(id)||!validId(turnId)||!validId(requestId)||typeof text!=='string'||!text.trim()||text.length>3000)throw error('请输入具体需求');if(this.jobs.has(id)){const old=this.jobs.get(id);if(old.text!==text||old.turnId!==turnId)throw error('Task id already used',409);return old;}if(this.jobs.size>=100)throw error('当前任务记录已满',429);
  const j={id,turnId,requestId,text,history:history.slice(-8).filter(m=>m&&['user','assistant'].includes(m.role)&&typeof m.content==='string').map(m=>({role:m.role,content:m.content.slice(0,2000)})),state:'queued',revision:0,generation:1,events:[],artifacts:[],reply:'',pending:null};this.jobs.set(id,j);this.event(j,'queued','收到，我会根据你的要求处理。');this.queue=this.queue.then(()=>this.run(j,1));return j;}
 async run(j,generation){if(j.generation!==generation||j.state==='cancelled')return;const controller=new AbortController();const control={controller,resolve:null,generation};this.controls.set(j.id,control);j.state='running';this.event(j,'running','正在理解需求并检查工作区');
  const active=()=>j.generation===generation&&j.state!=='cancelled';
  try{const r=await this.adapter.execute({text:j.text,history:j.history,turnId:j.turnId,requestId:j.requestId,signal:controller.signal,
   onMessage:text=>{if(active()){j.reply=text.slice(0,8000);j.revision++;this.persist(j);}},
   onEvent:e=>{if(active()){if(e.type==='route'&&e.route)j.route=e.route;this.event(j,e.type,e.summary,e.tool?{tool:e.tool}:{});}},
   onArtifacts:items=>{this.capture(j,items);},
   onApproval:proposal=>{if(!active())return false;if(!validId(proposal.approvalId)||!/^[a-f0-9]{64}$/.test(proposal.digest)||!Array.isArray(proposal.changes)||proposal.changes.length>10)throw error('无效改动计划');j.pending=proposal;j.state='waiting-approval';this.event(j,'waiting-approval',proposal.summary);return new Promise(resolve=>control.resolve=resolve);}
  });if(!active())return;j.reply=r.text||j.reply;j.decision=r.decision;j.route=r.route||null;j.pending=null;j.state='completed';this.event(j,'completed',j.artifacts.length?'操作已完成，文件已校验':'已回复');}
  catch(e){if(active()){j.state='failed';j.pending=null;j.error=/^[A-Z_]+$/.test(e.code||'')?e.code:'TASK_FAILED';if(Number.isInteger(e.httpStatus))j.httpStatus=e.httpStatus;if(typeof e.detail==='string')j.errorDetail=e.detail.slice(0,600);this.event(j,'failed','本次处理未完成；已完成的文件操作会保留在记录中。');}}
  finally{control.resolve?.(false);if(this.controls.get(j.id)===control)this.controls.delete(j.id);}
 }
 capture(j,items){if(!Array.isArray(items)||items.length>30)return;for(const item of items){if(!item||!['create','create_xlsx','create_image','create_video','replace','move'].includes(item.op)||typeof item.path!=='string'||!/^[a-f0-9]{64}$/.test(item.sha256||''))continue;const prior=j.artifacts.find(a=>a.path===item.path&&a.sha256===item.sha256);if(prior)continue;const content=this.files.bytes(item.path);if(createHash('sha256').update(content).digest('hex')!==item.sha256)continue;const id=randomUUID(),name=path.basename(item.path);writeFileSync(path.join(this.downloads,id),content,{flag:'wx',mode:0o600});j.artifacts.push({id,path:item.path,op:item.op,bytes:content.length,sha256:item.sha256,name,url:'/api/conversation-files/'+id});this.event(j,'artifact',`${item.op}: ${item.path} · ${content.length} 字节`);}}
 approve(id,{approvalId,approved}){const j=this.jobs.get(id),control=this.controls.get(id);if(!j||j.state!=='waiting-approval'||j.pending?.approvalId!==approvalId||!control?.resolve||typeof approved!=='boolean')throw error('计划已变化，请查看最新操作后确认',409);const resolve=control.resolve;control.resolve=null;j.pending=null;j.state='running';this.event(j,approved?'approved':'declined',approved?'你已确认这份具体计划，开始执行':'这份计划未获确认，不会执行这些改动');resolve(approved);return j;}
 amend(id,text){const j=this.jobs.get(id);if(!j||!['queued','running','waiting-approval'].includes(j.state))throw error('任务已经结束，请发送新需求',409);if(typeof text!=='string'||!text.trim()||text.length>2000||j.text.length+text.length>3500)throw error('补充内容过长');const c=this.controls.get(id);j.generation++;c?.resolve?.(false);c?.controller.abort();j.text+='\n用户补充（优先于旧要求，先检查已完成文件，不重复执行）：'+text;j.requestId=randomUUID();j.pending=null;j.state='queued';this.event(j,'updated','已收到补充，撤销尚未执行的旧计划，重新评估当前文件');const generation=j.generation;this.queue=this.queue.then(()=>this.run(j,generation));return j;}
 cancel(id){const j=this.jobs.get(id);if(!j)return null;if(['queued','running','waiting-approval'].includes(j.state)){const c=this.controls.get(id);j.state='cancelled';j.pending=null;c?.resolve?.(false);c?.controller.abort();this.event(j,'cancelled','任务已取消；此前已完成的改动保留');}return j;}
 public(j){if(!j)return null;const {history,text,...view}=j;return view;}
 artifact(id){for(const j of this.jobs.values()){const a=j.artifacts.find(a=>a.id===id);if(a)return {...a,file:path.join(this.downloads,id)};}return null;}
 close(){this.closed=true;for(const j of this.jobs.values())this.cancel(j.id);}
}
